# Generated by Django 6.0.3 on 2026-05-07 00:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=300, verbose_name='color')),
                ('color_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'color_products',
                'verbose_name_plural': 'color_products',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='Header_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='موضوع هدر سایت', max_length=150)),
                ('color_code', models.CharField(max_length=10)),
                ('right_text', models.CharField(max_length=100)),
                ('left_text', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('active', 'active'), ('repose', 'repose')], default='repose', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='created')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_category_image/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='created')),
                ('image', models.ImageField(blank=True, null=True, upload_to='secondaty_category_image/', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nat_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'nat_code_must_be_10_digits'), django.core.validators.MaxLengthValidator(10, 'nat_code_must_be_10_digits')], verbose_name='nat_code')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='birth_date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('address_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='address_code')),
                ('phonenumber', models.CharField(max_length=11, verbose_name='phone_number')),
                ('receiver', models.CharField(max_length=300, verbose_name='receiver')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('address_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='address_code')),
                ('phonenumber', models.CharField(max_length=11, verbose_name='phone_number')),
                ('receiver', models.CharField(max_length=300, verbose_name='receiver')),
                ('date', django_jalali.db.models.jDateField(verbose_name='delivery_date')),
                ('clock', models.CharField(max_length=300, verbose_name='delivery_time')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('total_price', models.PositiveIntegerField(verbose_name='total_price')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('state', models.CharField(choices=[('payed', 'payed'), ('paying', 'paying'), ('unpay', 'unpaid')], default='paying', max_length=6, verbose_name='state')),
                ('authority', models.CharField(blank=True, max_length=200, null=True, verbose_name='authority')),
                ('ref_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ref_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='HandOverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='date')),
                ('clock', models.CharField(max_length=300, verbose_name='time')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'handover_order',
                'verbose_name_plural': 'handover_orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('introduction', models.TextField(verbose_name='introduction')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='weight')),
                ('dimensions', models.CharField(max_length=150, verbose_name='dimensions')),
                ('more_details', models.TextField(verbose_name='more_details')),
                ('old_price', models.PositiveBigIntegerField(default=0, verbose_name='oldprice')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='stock')),
                ('wood_kind', models.CharField(default='MDF', max_length=300, verbose_name='wood_kind')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='updated_at')),
                ('off', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='off')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='main.maincategory', verbose_name='main-category')),
                ('color', models.ManyToManyField(related_name='products', to='main.colorproduct', verbose_name='color')),
                ('features', models.ManyToManyField(blank=True, related_name='products', to='main.feature', verbose_name='features')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='products'),
        ),
        migrations.CreateModel(
            name='Image_profile_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_image/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='images')),
            ],
            options={
                'verbose_name': 'product_image',
                'verbose_name_plural': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('state', models.CharField(choices=[('c', 'confirmed'), ('p', 'pending'), ('r', 'rejected')], default='p', max_length=1, verbose_name='state')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(related_name='users_by_favorite', to='main.product', verbose_name='favorite_products'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='order_basket',
            field=models.ManyToManyField(related_name='users_by_orderbasket', to='main.product', verbose_name='orderbasket'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('state', models.CharField(choices=[('c', 'confirmed'), ('p', 'pending'), ('r', 'rejected')], default='p', max_length=1, verbose_name='state')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True, verbose_name='updated_at')),
                ('admin_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='admin_answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.AddField(
            model_name='maincategory',
            name='secondary_category',
            field=models.ManyToManyField(to='main.secondarycategory'),
        ),
    ]
