# Generated by Django 6.0.3 on 2026-05-07 00:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecondaryCategory',
            new_name='CategorySecondary',
        ),
        migrations.CreateModel(
            name='CategoryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='created')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_category_image/', verbose_name='image')),
                ('secondary_category', models.ManyToManyField(related_name='categories_main', to='main.categorysecondary')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.categorymain', verbose_name='main-category'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
