# Generated by Django 6.0.3 on 2026-05-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.categorymain', verbose_name='main-category'),
        ),
    ]
