# Generated by Django 6.0.3 on 2026-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymain',
            name='icone',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
