# Generated by Django 6.0.3 on 2026-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorymain_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_image/', verbose_name='image')),
                ('title', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
