# Generated by Django 6.0.3 on 2026-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='blog_image/', verbose_name='image')),
                ('created', models.DateTimeField(auto_now=True)),
                ('upadated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
