# Generated by Django 6.0.3 on 2026-05-08 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customuser_order_basket_orderbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbasket',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_basket', to='main.colorproduct'),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='prodcut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_basket', to='main.product'),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
