# Generated by Django 6.0.3 on 2026-05-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_orderbasket_color_alter_orderbasket_prodcut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbasket',
            old_name='prodcut',
            new_name='product',
        ),
    ]
