# Generated by Django 6.0.3 on 2026-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_prodcut_orderbasket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_number_order',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
