# Generated by Django 6.0.3 on 2026-05-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_max_number_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_main',
        ),
        migrations.AddField(
            model_name='product',
            name='category_second',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.categorysecondary', verbose_name='secondary-category'),
        ),
    ]
