# Generated by Django 5.2.14 on 2026-05-12 01:37

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('main', '0014_addressinfo_city_addressinfo_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='address_code'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='receiver'),
        ),
    ]
