# Generated by Django 5.2.14 on 2026-05-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_address_order_address_code_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_top',
            name='color_code',
        ),
        migrations.AddField(
            model_name='header_top',
            name='image',
            field=models.ImageField(default='default.png', upload_to='header_images/', verbose_name='image'),
        ),
    ]
