# Generated by Django 5.2.14 on 2026-05-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_header_top_color_code_header_top_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header_top',
            name='left_text',
        ),
        migrations.RemoveField(
            model_name='header_top',
            name='right_text',
        ),
    ]
