# Generated by Django 5.2.14 on 2026-05-26 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_header_top_left_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AdSection_image/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(choices=[('active', 'active'), ('repose', 'repose')], default='repose', max_length=6)),
                ('category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymain')),
                ('image', models.ManyToManyField(to='main.aditem')),
            ],
        ),
    ]
