# Generated by Django 5.2.14 on 2026-05-30 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='attempts'),
        ),
        migrations.AddField(
            model_name='otp',
            name='code_hash',
            field=models.CharField(default=1, max_length=255, verbose_name='code_hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='expires_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='send_count'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='phone'),
        ),
    ]
