# Generated by Django 5.2.14 on 2026-06-03 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='category_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorymain'),
        ),
    ]
