# Generated by Django 5.2.14 on 2026-06-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sliderimage_category_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
