# Generated by Django 5.2.14 on 2026-06-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
    ]
