# Generated by Django 5.2.14 on 2026-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('payed', 'payed'), ('paying', 'paying'), ('unpay', 'unpaid'), ('cash_on_delivery', 'cash_on_delivery')], default='unpay', max_length=16, verbose_name='state'),
        ),
    ]
