# Generated by Django 5.2.14 on 2026-06-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_blog_upadated_blog_footer_blog_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='image',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_image/desktop/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_image/mobile/', verbose_name='image'),
        ),
    ]
