# Generated by Django 5.2.14 on 2026-06-13 21:32

import django.core.validators
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_sliderimage_image_sliderimage_desktop_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_discount_amount', models.PositiveIntegerField(verbose_name='حداکثر مبلغ تخفیف')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='حداکثر تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('expire_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('users', models.ManyToManyField(blank=True, related_name='used_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربران استفاده کننده')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
    ]
