# Generated by Django 5.2.14 on 2026-06-13 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_after_days', models.PositiveSmallIntegerField(default=10, verbose_name='شروع از چند روز بعد')),
                ('visible_days', models.PositiveSmallIntegerField(default=10, verbose_name='تعداد روزهای قابل نمایش')),
                ('max_orders_per_day', models.PositiveSmallIntegerField(default=10, verbose_name='حداکثر سفارش روزانه')),
            ],
            options={
                'verbose_name': 'تنظیمات تحویل',
                'verbose_name_plural': 'تنظیمات تحویل',
            },
        ),
        migrations.AlterModelOptions(
            name='handoverorder',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'handover_order', 'verbose_name_plural': 'handover_orders'},
        ),
        migrations.RemoveField(
            model_name='handoverorder',
            name='clock',
        ),
        migrations.AddField(
            model_name='handoverorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
