# Generated by Django 5.2.14 on 2026-06-14 01:53

import django.db.models.deletion
import django_jalali.db.models
import iranian_cities.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('main', '0032_deliverysettings_alter_handoverorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='clock',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=iranian_cities.fields.ProvinceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('payed', 'payed'), ('paying', 'paying'), ('unpay', 'unpaid'), ('cash_on_delivery', 'cash_on_delivery')], default='unpay', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
