# Generated by Django 5.2.14 on 2026-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_order_options_remove_order_clock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='used_as_accessory_for', to='main.product', verbose_name='لوازم جانبی'),
        ),
        migrations.AddField(
            model_name='product',
            name='body_color',
            field=models.ManyToManyField(related_name='products_body_color', to='main.colorproduct', verbose_name='رنگ بدنه'),
        ),
        migrations.AddField(
            model_name='product',
            name='door_color',
            field=models.ManyToManyField(related_name='products_door_color', to='main.colorproduct', verbose_name='رنگ در'),
        ),
    ]
