# Generated by Django 5.2.14 on 2026-06-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_product_accessories_product_body_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='body_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems_body', to='main.colorproduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='door_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems_door', to='main.colorproduct'),
        ),
    ]
