# Generated by Django 5.2.14 on 2026-06-14 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_orderitem_color_orderitem_body_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbasket',
            name='body_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderbasket_body', to='main.colorproduct'),
        ),
        migrations.AddField(
            model_name='orderbasket',
            name='door_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderbasket_door', to='main.colorproduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.colorproduct'),
        ),
    ]
