# Generated by Django 5.2.14 on 2026-06-14 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_orderbasket_body_color_orderbasket_door_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_type',
            field=models.CharField(choices=[('single', 'تک رنگ'), ('double', 'دو رنگ')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderbasket',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_basket', to='main.colorproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='body_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems_body', to='main.colorproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems_single', to='main.colorproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='door_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems_door', to='main.colorproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
