# Generated by Django 5.2.14 on 2026-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_product_color_type_alter_orderbasket_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body_color',
            field=models.ManyToManyField(blank=True, related_name='products_body_color', to='main.colorproduct', verbose_name='رنگ بدنه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_color',
            field=models.ManyToManyField(blank=True, related_name='products_door_color', to='main.colorproduct', verbose_name='رنگ در'),
        ),
    ]
