# Generated by Django 5.2.14 on 2026-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_product_body_color_alter_product_door_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.colorproduct', verbose_name='color'),
        ),
    ]
