# Generated by Django 5.2.14 on 2026-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellersProuducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='best_sellers', to='main.product', verbose_name='پر فروش ترین محصولات')),
            ],
        ),
        migrations.CreateModel(
            name='LatestProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='lastest', to='main.product', verbose_name='جدید ترین محصولات')),
            ],
        ),
    ]
