# Generated by Django 5.2.14 on 2026-08-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_bestsellersprouducts_latestproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=1500, verbose_name='dimensions'),
        ),
    ]
